#!/bin/bash

echo "🚀 INVESTOR DASHBOARD FIX - STEP BY STEP"
echo "=========================================="
echo ""
echo "Masalah: Investor dashboard masih menggunakan mock data"
echo "Solusi: Jalankan migration untuk menambahkan data investor real"
echo ""
echo "📋 STATUS SAAT INI:"
echo "✅ 4 project karbon sudah dibuat"
echo "❌ Kolom investor belum ada di tabel"
echo "❌ Data investor belum diisi"
echo ""
echo "🔧 LANGKAH-LANGKAH:"
echo ""
echo "1. JALANKAN MIGRATION SQL DI SUPABASE DASHBOARD"
echo "   --------------------------------------------"
echo "   a. Buka: https://supabase.com/dashboard"
echo "   b. Login → Pilih project: saelrsljpneclsbfdxfy"
echo "   c. SQL Editor → New query"
echo "   d. Copy-paste SQL dari file:"
echo "      supabase/migrations/202602100729_fix_investor_dashboard_corrected.sql"
echo "   e. Klik 'Run'"
echo ""
echo "2. UPDATE DATA INVESTOR"
echo "   --------------------"
echo "   python3 update_investor_data_corrected.py"
echo ""
echo "3. VERIFIKASI"
echo "   ----------"
echo "   python3 verify_investor_dashboard_final.py"
echo ""
echo "4. CEK DASHBOARD"
echo "   -------------"
echo "   Buka: http://localhost:3000/id/dashboard/investor"
echo ""
echo "🎯 HASIL YANG DIHARAPKAN:"
echo "   - Data source: 'database_views' atau 'database_direct' (bukan 'fallback')"
echo "   - 4 project karbon dengan data investor real"
echo "   - Investment amounts, ROI, carbon sequestration estimates"
echo ""
echo "📁 FILE YANG DISEDIAKAN:"
echo "   - MIGRATION_INSTRUCTIONS.md          : Instruksi lengkap"
echo "   - update_investor_data_corrected.py  : Script update data"
echo "   - verify_investor_dashboard_final.py : Script verifikasi"
echo ""
echo "⚠️  TROUBLESHOOTING:"
echo "   Jika migration gagal:"
echo "   - Error 'column already exists': Abaikan, kolom sudah ada"
echo "   - Error 'view already exists': Abaikan, view sudah ada"
echo "   - Error lain: Cek file MIGRATION_INSTRUCTIONS.md"
echo ""
echo "=========================================="
echo "Selesai! Investor dashboard sekarang akan menggunakan data real dari database."
echo ""

# Optional: Ask user if they want to run verification now
read -p "Jalankan verifikasi sekarang? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Menjalankan verifikasi..."
    python3 verify_investor_dashboard_final.py
fi