#!/bin/bash

echo "======================================================"
echo "INVESTOR DASHBOARD MIGRATION SCRIPT"
echo "======================================================"
echo ""
echo "MASALAH: Investor dashboard menggunakan mock data"
echo "SOLUSI: Jalankan migration SQL untuk menambahkan kolom investor"
echo "        dan membuat views terintegrasi"
echo ""
echo "Migration file: supabase/migrations/202602060943_fix_investor_dashboard_mock_data.sql"
echo ""

# Tampilkan preview migration SQL
echo "📋 PREVIEW MIGRATION SQL (10 baris pertama):"
echo "------------------------------------------------------"
head -20 supabase/migrations/202602060943_fix_investor_dashboard_mock_data.sql
echo "..."
echo ""

echo "🚀 INSTRUKSI MIGRATION MANUAL:"
echo "======================================================"
echo ""
echo "1. BUKA SUPABASE DASHBOARD:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. PILIH PROJECT ANDA:"
echo "   Project: saelrsljpneclsbfdxfy"
echo "   URL: https://saelrsljpneclsbfdxfy.supabase.co"
echo ""
echo "3. BUKA SQL EDITOR:"
echo "   - Klik 'SQL Editor' di sidebar kiri"
echo "   - Klik 'New query'"
echo ""
echo "4. COPY-PASTE SQL BERIKUT:"
echo "------------------------------------------------------"
cat supabase/migrations/202602060943_fix_investor_dashboard_mock_data.sql
echo "------------------------------------------------------"
echo ""
echo "5. KLIK 'RUN'"
echo ""
echo "6. VERIFIKASI MIGRATION:"
echo "   Setelah migration selesai, jalankan query verifikasi:"
echo ""
echo "   -- Cek apakah views sudah dibuat"
echo "   SELECT table_name, table_type "
echo "   FROM information_schema.tables "
echo "   WHERE table_name IN ('v_investor_dashboard_data', 'v_investor_dashboard_summary', 'mv_investor_performance_metrics');"
echo ""
echo "   -- Cek kolom investor di carbon_projects"
echo "   SELECT column_name, data_type "
echo "   FROM information_schema.columns "
echo "   WHERE table_name = 'carbon_projects' "
echo "   AND column_name IN ('investment_amount', 'roi_percentage', 'carbon_sequestration_estimated');"
echo ""
echo "7. TEST FRONTEND:"
echo "   - Buka http://localhost:3000/id/dashboard/investor"
echo "   - Refresh halaman"
echo "   - Periksa data source indicator di header"
echo "   - Seharusnya menunjukkan 'database_views' bukan 'fallback'"
echo ""
echo "======================================================"
echo "ALTERNATIF: JIKA INGIN OTOMATIS, UPDATE SERVICE ROLE KEY"
echo "======================================================"
echo ""
echo "1. Dapatkan service role key baru dari Supabase Dashboard:"
echo "   - Settings → API"
echo "   - Copy 'service_role' key"
echo ""
echo "2. Update .env.local:"
echo "   SUPABASE_SERVICE_ROLE_KEY=<key-baru>"
echo ""
echo "3. Jalankan migration otomatis:"
echo "   node scripts/run-sql-migration.js supabase/migrations/202602060943_fix_investor_dashboard_mock_data.sql"
echo ""
echo "======================================================"
echo "SUPPORT:"
echo "======================================================"
echo "Jika ada masalah:"
echo "1. Cek error log di Supabase Dashboard → Logs"
echo "2. Pastikan user memiliki permission untuk create views"
echo "3. Pastikan tabel carbon_projects sudah ada"
echo ""

# Buat file SQL terpisah untuk kemudahan
cp supabase/migrations/202602060943_fix_investor_dashboard_mock_data.sql investor_migration_ready.sql
echo "✅ File SQL siap: investor_migration_ready.sql"
echo "   Gunakan file ini untuk copy-paste ke Supabase SQL Editor"