-- Migration: Create chat_logs table for AI chatbot interactions
-- Date: 2026-01-19
-- Description: Stores chat interactions between users and AI assistant for auditing and history

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create chat_logs table
CREATE TABLE IF NOT EXISTS chat_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    user_role VARCHAR(50) NOT NULL,
    language VARCHAR(10) NOT NULL CHECK (language IN ('id', 'en', 'zh-TW')),
    user_message TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    tokens_used INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_chat_logs_user_id ON chat_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_logs_created_at ON chat_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_logs_language ON chat_logs(language);

-- Enable Row Level Security (RLS)
ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Users can only see their own chat logs
CREATE POLICY "Users can view own chat logs" ON chat_logs
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own chat logs (this will be done by server)
CREATE POLICY "Users can insert own chat logs" ON chat_logs
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Only admins can update or delete chat logs (for moderation)
CREATE POLICY "Only admins can update chat logs" ON chat_logs
    FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    );

CREATE POLICY "Only admins can delete chat logs" ON chat_logs
    FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    );

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_chat_logs_updated_at 
    BEFORE UPDATE ON chat_logs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add comment
COMMENT ON TABLE chat_logs IS 'Stores chat interactions between users and AI assistant for the Social Forestry Information System';
COMMENT ON COLUMN chat_logs.user_id IS 'References auth.users.id - the user who initiated the chat';
COMMENT ON COLUMN chat_logs.user_role IS 'Role of the user at the time of interaction (admin, viewer, monev, etc.)';
COMMENT ON COLUMN chat_logs.language IS 'Language used in the conversation (id=Indonesian, en=English, zh-TW=Chinese Traditional)';
COMMENT ON COLUMN chat_logs.user_message IS 'The message sent by the user';
COMMENT ON COLUMN chat_logs.ai_response IS 'The response generated by the AI assistant';
COMMENT ON COLUMN chat_logs.tokens_used IS 'Number of tokens consumed for this interaction';
COMMENT ON COLUMN chat_logs.created_at IS 'Timestamp when the chat log was created';
COMMENT ON COLUMN chat_logs.updated_at IS 'Timestamp when the chat log was last updated';
